
phoneme:
  dictionary: text/dutch_cmudict
  moa: ["Vowel","Plosive","Nasal","Fricative","Affricates","Approximant"]
  poa: ["Vowel","Bilabial","Labiodental","Dental","Alveolar","Postalveolar","Palatal","Velar","Glottal"]
  alternative_cmudict: True