
phoneme:
  dictionary: text/dutch_cmudict
  moa: ["Vowel","Plosive","Nasal","Fricative","Approximant"]
  poa: ["Vowel","Bilabial","Labiodental","Alveolar","Postalveolar","Palatal","Velar","Glottal"]
  alternative_cmudict: True
  phoneme_name: "CGN-Phone"
  conversion_mapping: "PhoneSet_dutch.csv"
  dutch_oov_rule: True
asr: "kaldi"